// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: orderbook.proto

package orderbook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Level struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level) Reset() {
	*x = Level{}
	mi := &file_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *Level) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Level) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 파일에 저장될 유일한 메시지: 오더북 스냅샷
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTime     int64                  `protobuf:"varint,1,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"` // 데이터 수신 시간 (UTC ms)
	LastUpdateId  int64                  `protobuf:"varint,2,opt,name=last_update_id,json=lastUpdateId,proto3" json:"last_update_id,omitempty"`
	Bids          []*Level               `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*Level               `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *Snapshot) GetLastUpdateId() int64 {
	if x != nil {
		return x.LastUpdateId
	}
	return 0
}

func (x *Snapshot) GetBids() []*Level {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Snapshot) GetAsks() []*Level {
	if x != nil {
		return x.Asks
	}
	return nil
}

var File_orderbook_proto protoreflect.FileDescriptor

const file_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x0forderbook.proto\x12\torderbook\"9\n" +
	"\x05Level\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\"\x9b\x01\n" +
	"\bSnapshot\x12\x1d\n" +
	"\n" +
	"event_time\x18\x01 \x01(\x03R\teventTime\x12$\n" +
	"\x0elast_update_id\x18\x02 \x01(\x03R\flastUpdateId\x12$\n" +
	"\x04bids\x18\x03 \x03(\v2\x10.orderbook.LevelR\x04bids\x12$\n" +
	"\x04asks\x18\x04 \x03(\v2\x10.orderbook.LevelR\x04asksB\rZ\v./orderbookb\x06proto3"

var (
	file_orderbook_proto_rawDescOnce sync.Once
	file_orderbook_proto_rawDescData []byte
)

func file_orderbook_proto_rawDescGZIP() []byte {
	file_orderbook_proto_rawDescOnce.Do(func() {
		file_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderbook_proto_rawDesc), len(file_orderbook_proto_rawDesc)))
	})
	return file_orderbook_proto_rawDescData
}

var file_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orderbook_proto_goTypes = []any{
	(*Level)(nil),    // 0: orderbook.Level
	(*Snapshot)(nil), // 1: orderbook.Snapshot
}
var file_orderbook_proto_depIdxs = []int32{
	0, // 0: orderbook.Snapshot.bids:type_name -> orderbook.Level
	0, // 1: orderbook.Snapshot.asks:type_name -> orderbook.Level
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orderbook_proto_init() }
func file_orderbook_proto_init() {
	if File_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderbook_proto_rawDesc), len(file_orderbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderbook_proto_goTypes,
		DependencyIndexes: file_orderbook_proto_depIdxs,
		MessageInfos:      file_orderbook_proto_msgTypes,
	}.Build()
	File_orderbook_proto = out.File
	file_orderbook_proto_goTypes = nil
	file_orderbook_proto_depIdxs = nil
}
